baseurl = "http://fintrospect.io"
title = "fintrospect"
languageCode = "en-us"
googleAnalytics = ""

[params]
    author = "fintrospect"
    style = "blue"
    copyright = "Copyright (c) 2015 - 2016, YourCompany; all rights reserved."
    date_format = "2100-01-01"
    logo = "img/logo.png"

[[params.menu]]
    name = "overview"
    url  = "/overview"

[[params.menu]]
    name = "get it"
    url  = "/get-it"

[[params.menu]]
    name = "guide"
    url  = "/guide"

[[params.menu]]
    name = "cookbook"
    url  = "/cookbook"

[[params.menu]]
    name = "api"
    url  = "/api"

[[params.menu]]
    img = "/img/github-20px.png"
    url  = "https://github.com/daviddenton/fintrospect"

[[params.menu]]
    img = "https://api.bintray.com/packages/fintrospect/maven/fintrospect-core/images/download.svg"
    url  = "https://bintray.com/fintrospect/maven/fintrospect-core/_latestVersion"

[[params.menu]]
    img = "https://travis-ci.org/daviddenton/fintrospect.svg?branch=master"
    url  = "https://travis-ci.org/daviddenton/fintrospect"

[[params.menu]]
    img = "https://coveralls.io/repos/daviddenton/fintrospect/badge.svg?branch=master"
    url  = "https://coveralls.io/github/daviddenton/fintrospect?branch=master"
