baseurl = "http://fintrospect.io/"
title = "fintrospect"
languageCode = "en-us"
googleAnalytics = ""
theme = "hugo-universal-theme"
defaultContentLanguage = "en"
paginate = 10

[menu]

[[menu.main]]
    name = "overview"
    url  = "/overview"
    weight = 1

[[menu.main]]
    name = "get it"
    url  = "/get-it"
    weight = 2

[[menu.main]]
    name = "guide"
    url  = "/guide"
    weight = 3

[[menu.main]]
    name = "cookbook"
    url  = "/cookbook"
    weight = 4

[[menu.main]]
    name = "api"
    url  = "/api"
    weight = 5

[[menu.main]]
    name = "gh"
    img = "/img/github-20px.png"
    url  = "https://github.com/daviddenton/fintrospect"
    weight = 6

[[menu.main]]
    name = "dl"
    img = "https://api.bintray.com/packages/fintrospect/maven/fintrospect-core/images/download.svg"
    url  = "https://bintray.com/fintrospect/maven/fintrospect-core/_latestVersion"
    weight = 7

[[menu.main]]
    name = "ci"
    img = "https://travis-ci.org/daviddenton/fintrospect.svg?branch=master"
    url  = "https://travis-ci.org/daviddenton/fintrospect"
    weight = 8

[[menu.main]]
    name = "cc"
    img = "https://coveralls.io/repos/daviddenton/fintrospect/badge.svg?branch=master"
    url  = "https://coveralls.io/github/daviddenton/fintrospect?branch=master"
    weight = 9

[Permalinks]
    cookbook = "/cookbook/:filename/"

[params.carousel]
    enable = true

[params.features]
    enable = true
